server:
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: on_param
    include-exception: false
  port: 8080

spring:
  jpa:
    show-sql: true
    properties.properties.hibernate.format_sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
      settings:
        trace: false
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  liquibase:
    enabled: true
    change-log: classpath:db/db.changelog-master.xml
    drop-first: true
  messages:
    basename: classpath:localization/message

logging:
  level:
    org.hibernate.type.descripter.sql: trace
    liquibase: DEBUG
